// flow-typed signature: e2739bb17e7f9aab94d93b67721bc5ba
// flow-typed version: <<STUB>>/mockery_v^2.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mockery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mockery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mockery/mockery' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mockery/mockery.js' {
  declare module.exports: $Exports<'mockery/mockery'>;
}
