// flow-typed signature: 6da3e8702218bc708257fbfb44b32442
// flow-typed version: <<STUB>>/querystringify_v0.0.4/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'querystringify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'querystringify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'querystringify/index' {
  declare module.exports: $Exports<'querystringify'>;
}
declare module 'querystringify/index.js' {
  declare module.exports: $Exports<'querystringify'>;
}
