// flow-typed signature: 3f30f94d0afed27869346278d8075f2e
// flow-typed version: <<STUB>>/react-native-keyboard-spacer_v^0.3.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-keyboard-spacer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-keyboard-spacer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-keyboard-spacer/KeyboardSpacer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-keyboard-spacer/KeyboardSpacer.js' {
  declare module.exports: $Exports<'react-native-keyboard-spacer/KeyboardSpacer'>;
}
