// flow-typed signature: 427423715ff3fcd3bede4fe5540373f8
// flow-typed version: <<STUB>>/reactotron-apisauce_v^1.5.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactotron-apisauce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactotron-apisauce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactotron-apisauce/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactotron-apisauce/dist/index.js' {
  declare module.exports: $Exports<'reactotron-apisauce/dist/index'>;
}
