// flow-typed signature: ff82268a190dc1455532b384ec360c7c
// flow-typed version: <<STUB>>/realm_v^1.0.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'realm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'realm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'realm/lib/browser/base64' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/collections' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/constants' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/index' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/lists' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/objects' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/results' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/rpc' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/session' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/user' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/util' {
  declare module.exports: any;
}

declare module 'realm/lib/collection-methods' {
  declare module.exports: any;
}

declare module 'realm/lib/errors' {
  declare module.exports: any;
}

declare module 'realm/lib/extensions' {
  declare module.exports: any;
}

declare module 'realm/lib/index' {
  declare module.exports: any;
}

declare module 'realm/lib/management-schema' {
  declare module.exports: any;
}

declare module 'realm/lib/submit-analytics' {
  declare module.exports: any;
}

declare module 'realm/lib/user-methods' {
  declare module.exports: any;
}

declare module 'realm/react-native/index' {
  declare module.exports: any;
}

declare module 'realm/react-native/listview' {
  declare module.exports: any;
}

declare module 'realm/scripts/install' {
  declare module.exports: any;
}

declare module 'realm/tests/index' {
  declare module.exports: any;
}

declare module 'realm/tests/js/asserts' {
  declare module.exports: any;
}

declare module 'realm/tests/js/async-tests' {
  declare module.exports: any;
}

declare module 'realm/tests/js/encryption-tests' {
  declare module.exports: any;
}

declare module 'realm/tests/js/index' {
  declare module.exports: any;
}

declare module 'realm/tests/js/list-tests' {
  declare module.exports: any;
}

declare module 'realm/tests/js/migration-tests' {
  declare module.exports: any;
}

declare module 'realm/tests/js/object-tests' {
  declare module.exports: any;
}

declare module 'realm/tests/js/query-tests' {
  declare module.exports: any;
}

declare module 'realm/tests/js/realm-tests' {
  declare module.exports: any;
}

declare module 'realm/tests/js/results-tests' {
  declare module.exports: any;
}

declare module 'realm/tests/js/schemas' {
  declare module.exports: any;
}

declare module 'realm/tests/js/session-tests' {
  declare module.exports: any;
}

declare module 'realm/tests/js/user-tests' {
  declare module.exports: any;
}

declare module 'realm/tests/js/worker-tests-script' {
  declare module.exports: any;
}

declare module 'realm/tests/js/worker' {
  declare module.exports: any;
}

declare module 'realm/tests/spec/helpers/mock_realm' {
  declare module.exports: any;
}

declare module 'realm/tests/spec/helpers/reporters' {
  declare module.exports: any;
}

declare module 'realm/tests/spec/helpers/setup-module-path' {
  declare module.exports: any;
}

declare module 'realm/tests/spec/sync_integration_tests' {
  declare module.exports: any;
}

declare module 'realm/tests/spec/unit_tests' {
  declare module.exports: any;
}

declare module 'realm/tests/test-runners/ava/test' {
  declare module.exports: any;
}

declare module 'realm/tests/test-runners/jest/test' {
  declare module.exports: any;
}

declare module 'realm/tests/test-runners/mocha/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'realm/lib/browser/base64.js' {
  declare module.exports: $Exports<'realm/lib/browser/base64'>;
}
declare module 'realm/lib/browser/collections.js' {
  declare module.exports: $Exports<'realm/lib/browser/collections'>;
}
declare module 'realm/lib/browser/constants.js' {
  declare module.exports: $Exports<'realm/lib/browser/constants'>;
}
declare module 'realm/lib/browser/index.js' {
  declare module.exports: $Exports<'realm/lib/browser/index'>;
}
declare module 'realm/lib/browser/lists.js' {
  declare module.exports: $Exports<'realm/lib/browser/lists'>;
}
declare module 'realm/lib/browser/objects.js' {
  declare module.exports: $Exports<'realm/lib/browser/objects'>;
}
declare module 'realm/lib/browser/results.js' {
  declare module.exports: $Exports<'realm/lib/browser/results'>;
}
declare module 'realm/lib/browser/rpc.js' {
  declare module.exports: $Exports<'realm/lib/browser/rpc'>;
}
declare module 'realm/lib/browser/session.js' {
  declare module.exports: $Exports<'realm/lib/browser/session'>;
}
declare module 'realm/lib/browser/user.js' {
  declare module.exports: $Exports<'realm/lib/browser/user'>;
}
declare module 'realm/lib/browser/util.js' {
  declare module.exports: $Exports<'realm/lib/browser/util'>;
}
declare module 'realm/lib/collection-methods.js' {
  declare module.exports: $Exports<'realm/lib/collection-methods'>;
}
declare module 'realm/lib/errors.js' {
  declare module.exports: $Exports<'realm/lib/errors'>;
}
declare module 'realm/lib/extensions.js' {
  declare module.exports: $Exports<'realm/lib/extensions'>;
}
declare module 'realm/lib/index.js' {
  declare module.exports: $Exports<'realm/lib/index'>;
}
declare module 'realm/lib/management-schema.js' {
  declare module.exports: $Exports<'realm/lib/management-schema'>;
}
declare module 'realm/lib/submit-analytics.js' {
  declare module.exports: $Exports<'realm/lib/submit-analytics'>;
}
declare module 'realm/lib/user-methods.js' {
  declare module.exports: $Exports<'realm/lib/user-methods'>;
}
declare module 'realm/react-native/index.js' {
  declare module.exports: $Exports<'realm/react-native/index'>;
}
declare module 'realm/react-native/listview.js' {
  declare module.exports: $Exports<'realm/react-native/listview'>;
}
declare module 'realm/scripts/install.js' {
  declare module.exports: $Exports<'realm/scripts/install'>;
}
declare module 'realm/tests/index.js' {
  declare module.exports: $Exports<'realm/tests/index'>;
}
declare module 'realm/tests/js/asserts.js' {
  declare module.exports: $Exports<'realm/tests/js/asserts'>;
}
declare module 'realm/tests/js/async-tests.js' {
  declare module.exports: $Exports<'realm/tests/js/async-tests'>;
}
declare module 'realm/tests/js/encryption-tests.js' {
  declare module.exports: $Exports<'realm/tests/js/encryption-tests'>;
}
declare module 'realm/tests/js/index.js' {
  declare module.exports: $Exports<'realm/tests/js/index'>;
}
declare module 'realm/tests/js/list-tests.js' {
  declare module.exports: $Exports<'realm/tests/js/list-tests'>;
}
declare module 'realm/tests/js/migration-tests.js' {
  declare module.exports: $Exports<'realm/tests/js/migration-tests'>;
}
declare module 'realm/tests/js/object-tests.js' {
  declare module.exports: $Exports<'realm/tests/js/object-tests'>;
}
declare module 'realm/tests/js/query-tests.js' {
  declare module.exports: $Exports<'realm/tests/js/query-tests'>;
}
declare module 'realm/tests/js/realm-tests.js' {
  declare module.exports: $Exports<'realm/tests/js/realm-tests'>;
}
declare module 'realm/tests/js/results-tests.js' {
  declare module.exports: $Exports<'realm/tests/js/results-tests'>;
}
declare module 'realm/tests/js/schemas.js' {
  declare module.exports: $Exports<'realm/tests/js/schemas'>;
}
declare module 'realm/tests/js/session-tests.js' {
  declare module.exports: $Exports<'realm/tests/js/session-tests'>;
}
declare module 'realm/tests/js/user-tests.js' {
  declare module.exports: $Exports<'realm/tests/js/user-tests'>;
}
declare module 'realm/tests/js/worker-tests-script.js' {
  declare module.exports: $Exports<'realm/tests/js/worker-tests-script'>;
}
declare module 'realm/tests/js/worker.js' {
  declare module.exports: $Exports<'realm/tests/js/worker'>;
}
declare module 'realm/tests/spec/helpers/mock_realm.js' {
  declare module.exports: $Exports<'realm/tests/spec/helpers/mock_realm'>;
}
declare module 'realm/tests/spec/helpers/reporters.js' {
  declare module.exports: $Exports<'realm/tests/spec/helpers/reporters'>;
}
declare module 'realm/tests/spec/helpers/setup-module-path.js' {
  declare module.exports: $Exports<'realm/tests/spec/helpers/setup-module-path'>;
}
declare module 'realm/tests/spec/sync_integration_tests.js' {
  declare module.exports: $Exports<'realm/tests/spec/sync_integration_tests'>;
}
declare module 'realm/tests/spec/unit_tests.js' {
  declare module.exports: $Exports<'realm/tests/spec/unit_tests'>;
}
declare module 'realm/tests/test-runners/ava/test.js' {
  declare module.exports: $Exports<'realm/tests/test-runners/ava/test'>;
}
declare module 'realm/tests/test-runners/jest/test.js' {
  declare module.exports: $Exports<'realm/tests/test-runners/jest/test'>;
}
declare module 'realm/tests/test-runners/mocha/test.js' {
  declare module.exports: $Exports<'realm/tests/test-runners/mocha/test'>;
}
